In [9]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(1, 21).reshape(10, -1)
y = np.zeros(10)
y[7:] = 1

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

print(f"X_train:\n{X_train}\n\n")
print(f"X_train:\n{y_train}\n\n")
print(f"X_train:\n{X_test}\n\n")
print(f"X_train:\n{y_test}")

print(np.mean(y_train))
print(np.mean(y_test))


X_train:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


X_train:
[0. 0. 0. 0. 0. 0. 0. 1.]


X_train:
[[17 18]
 [19 20]]


X_train:
[1. 1.]
0.125
1.0


In [10]:
X = np.arange(1, 201).reshape(100, -1)
y = np.zeros(100)
y[70:] = 1

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=43
)

print(np.mean(y_train))
print(np.mean(y_test))

0.3
0.3
