In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

columns = [
    "Sample_code_number", "Clump_Thickness", "Uniformity_Cell_Size",
    "Uniformity_Cell_Shape", "Marginal_Adhesion", "Single_Epithelial_Cell_Size",
    "Bare_Nuclei", "Bland_Chromatin", "Normal_Nucleoli", "Mitoses", "Class"
]

df = pd.read_csv(
    "https://learn.zone01oujda.ma/api/content/root/01-edu_module/content/classification/data/breast-cancer-wisconsin.data",
    names=columns
)

df.replace("?", np.nan, inplace=True)
df = df.astype(float)
df.fillna(df.median(), inplace=True)
df.drop(columns=["Sample_code_number"], inplace=True)

X = df.drop(columns=["Class"])
y = df["Class"].astype(int)

print((y == 2).mean())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=43
)

print((y_test == 2).mean())
print((y_train == 2).mean())

clf = LogisticRegression(max_iter=1000, solver="liblinear")
clf.fit(X_train, y_train)

print(clf.predict(X_train)[:10])
print(clf.predict_proba(X_train)[:,1][:10])
print(clf.score(X_train, y_train))

print(clf.predict(X_test)[:10])
print(clf.predict_proba(X_test)[:,1][:10])
print(clf.score(X_test, y_test))

print(confusion_matrix(y_train, clf.predict(X_train)))
print(confusion_matrix(y_test, clf.predict(X_test)))


df.head()

0.6552217453505007
0.6571428571428571
0.6547406082289803
[4 2 4 2 2 2 2 4 2 2]
[0.99729702 0.02988973 0.99700878 0.03566896 0.04511416 0.02452524
 0.05333401 0.95182631 0.02723341 0.03023137]
0.9660107334525939
[2 2 2 4 2 4 2 2 2 4]
[0.04252921 0.34246394 0.0307827  0.61232745 0.01347699 0.99419559
 0.38987572 0.03317014 0.02033571 0.99587118]
0.9428571428571428
[[357   9]
 [ 10 183]]
[[90  2]
 [ 6 42]]


,Clump_Thickness,Uniformity_Cell_Size,Uniformity_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,5.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0,2.0
1,5.0,4.0,4.0,5.0,7.0,10.0,3.0,2.0,1.0,2.0
2,3.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0,2.0
3,6.0,8.0,8.0,1.0,3.0,4.0,3.0,7.0,1.0,2.0
4,4.0,1.0,1.0,3.0,2.0,1.0,3.0,1.0,1.0,2.0
