In [17]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

print(X_train_scaled.mean(axis=0))
print(X_train_scaled.std(axis=0))
X_train_scaled

[0. 0. 0.]
[1. 1. 1.]


array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [18]:

X_test = np.array([
    [ 2., -1.,  1.],
    [ 3.,  3., -1.],
    [ 1.,  1.,  1.]
])

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 1.22474487, -1.22474487,  0.53452248],
       [ 2.44948974,  3.67423461, -1.06904497],
       [ 0.        ,  1.22474487,  0.53452248]])