In [36]:
from sklearn.impute import SimpleImputer
import numpy as np

train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]

imp_mean = SimpleImputer(strategy="mean")
imp_mean.fit(train_data)

print(imp_mean.statistics_ == np.nanmean(train_data, axis=0))
imp_mean.statistics_

[ True  True  True]


array([ 4., 13.,  6.])

In [37]:
imp_mean.transform(train_data)

array([[ 7.,  6.,  5.],
       [ 4., 13.,  5.],
       [ 1., 20.,  8.]])

In [38]:
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

# imp_mean.fit(test_data)
imp_mean.transform(test_data)

array([[ 4.,  1.,  2.],
       [ 7., 13.,  9.],
       [ 4.,  2.,  4.]])