In [42]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.arange(1,21).reshape(10,-1)
y = np.arange(1,11)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

print(f"X_train:\n{X_train}\n\n")
print(f"X_train:\n{y_train}\n\n")
print(f"X_train:\n{X_test}\n\n")
print(f"X_train:\n{y_test}")

X_train:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


X_train:
[1 2 3 4 5 6 7 8]


X_train:
[[17 18]
 [19 20]]


X_train:
[ 9 10]
