In [ ]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelBinarizer

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

lb = LabelBinarizer()
y_train_multi_class = lb.fit_transform(y_train)
y_test_multi_class  = lb.transform(y_test)

print(y_train_multi_class[:10])

model = Sequential()
model.add(Dense(10, input_dim=4, activation="sigmoid"))
model.add(Dense(3, activation="softmax"))

model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model.fit(X_train_sc, y_train_multi_class, epochs=1000, batch_size=20, verbose=0)

loss, acc = model.evaluate(X_test_sc, y_test_multi_class, verbose=0)
print("Test accuracy:", acc)


[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Test accuracy: 0.9666666388511658
